version: '3'
services:
  # a sample app with metrics enabled
  app:
    container_name: app
    build:
      context: app
      dockerfile: Dockerfile
    stop_signal: SIGKILL
    ports:
      - "5000:5000"

  # dumb, random load generator
  generator:
    build:
      context: generator
      dockerfile: Dockerfile
    stop_signal: SIGKILL
    depends_on:
      - app

  # the Prometheus server
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v3.2.0
    volumes:
      - ./prometheus/config.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - app

  # Grafana for visualization
  grafana:
    image: grafana/grafana:11.5.2
    volumes:
      - ./grafana/config.ini:/etc/grafana/grafana.ini
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/default.yaml
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/default.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
