global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.gmail.com:587'  # Replace with your SMTP server
  smtp_from: 'jtreguer@gmail.com'     # Replace with your email
  smtp_auth_username: 'jtreguer@gmail.com'  # Replace with your email
  smtp_auth_password: 'your_app_password'     # Replace with your app password

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 5m
  # receiver: 'default-recei ver'
  receiver: 'email-notifications'

receivers:
  # - name: 'default-receiver'
  #   slack_configs:
  #     - api_url: 'https://hooks.slack.com/services/your/slack/webhook/url'
  #       channel: '#alerts'
  #       send_resolved: true
  - name: 'email-notifications'
    email_configs:
      - to: 'recipient_email@example.com'  # Replace with the recipient's email
