global:
  scrape_interval: 3s

  external_labels:
    monitor: "app"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "app"
    static_configs:
      - targets: ["app:5000"]

# Configure Alertmanager
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - "alertmanager:9093"

# Define alert rules
rule_files:
  - "./alerts.rules.yml"
